export const XNormalRegister_ABI = [
 {
  inputs: [{ internalType: "address", name: "target", type: "address" }],
  name: "AddressEmptyCode",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "implementation", type: "address" }],
  name: "ERC1967InvalidImplementation",
  type: "error",
 },
 { inputs: [], name: "ERC1967NonPayable", type: "error" },
 { inputs: [], name: "FailedInnerCall", type: "error" },
 { inputs: [], name: "InsufficientValue", type: "error" },
 { inputs: [], name: "InvalidInitialization", type: "error" },
 { inputs: [], name: "NotInitializing", type: "error" },
 {
  inputs: [{ internalType: "address", name: "owner", type: "address" }],
  name: "OwnableInvalidOwner",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "account", type: "address" }],
  name: "OwnableUnauthorizedAccount",
  type: "error",
 },
 { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
 {
  inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
  name: "UUPSUnsupportedProxiableUUID",
  type: "error",
 },
 {
  anonymous: false,
  inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }],
  name: "Initialized",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
   { indexed: true, internalType: "address", name: "newOwner", type: "address" },
  ],
  name: "OwnershipTransferred",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "string", name: "code", type: "string" },
   { indexed: false, internalType: "address", name: "addr", type: "address" },
  ],
  name: "RegisterByInviter",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }],
  name: "Upgraded",
  type: "event",
 },
 {
  inputs: [],
  name: "NRAmount",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
   { internalType: "string", name: "code", type: "string" },
  ],
  name: "NRWithInviter",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "NRWithoutInviter",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [],
  name: "QueenBee",
  outputs: [{ internalType: "contract IERC721", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "RC",
  outputs: [{ internalType: "contract IRegisterController", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "UPGRADE_INTERFACE_VERSION",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "airdrop",
  outputs: [{ internalType: "contract IAirdrop", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "autoUpgrade",
  outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "discount",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "generateCode",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "getCode",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "uint256", name: "layer", type: "uint256" },
  ],
  name: "getDividend",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "string", name: "code", type: "string" }],
  name: "getNRInfo",
  outputs: [
   { internalType: "address", name: "", type: "address" },
   { internalType: "uint32[3]", name: "", type: "uint32[3]" },
   { internalType: "uint256", name: "", type: "uint256" },
  ],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "getParent",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "string", name: "code", type: "string" },
   { internalType: "string", name: "name", type: "string" },
  ],
  name: "getPriceWithCode",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "string", name: "name", type: "string" },
  ],
  name: "getPriceWithoutCode",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint256", name: "", type: "uint256" },
   { internalType: "uint256", name: "", type: "uint256" },
  ],
  name: "infoByLayer",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint256", name: "_NRAmount", type: "uint256" },
   { internalType: "uint256", name: "_lock_", type: "uint256" },
  ],
  name: "initialize",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "", type: "address" }],
  name: "isManager",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "owner",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "prices",
  outputs: [{ internalType: "contract IPriceOracle", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "proxiableUUID",
  outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "renounceOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint32", name: "num", type: "uint32" }],
  name: "setAutoUpgrade",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
  name: "setCoef",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "value", type: "uint256" }],
  name: "setDiscount",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "div", type: "uint256" }],
  name: "setDividend",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint256", name: "level", type: "uint256" },
   { internalType: "uint256", name: "layer", type: "uint256" },
   { internalType: "uint256", name: "div", type: "uint256" },
  ],
  name: "setLayerDividend",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "bool", name: "state", type: "bool" },
  ],
  name: "setManager",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setQueenBee",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "contract IAirdrop", name: "addr", type: "address" }],
  name: "setTrustedAirdrop",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "contract IPriceOracle", name: "addr", type: "address" }],
  name: "setTrustedPriceOracle",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "contract IRegisterController", name: "addr", type: "address" }],
  name: "setTrustedRegisterController",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
  name: "transferOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "newImplementation", type: "address" },
   { internalType: "bytes", name: "data", type: "bytes" },
  ],
  name: "upgradeToAndCall",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [],
  name: "upgradeToManager",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 { inputs: [], name: "withdraw", outputs: [], stateMutability: "payable", type: "function" },
]