export const XRegistrarController_ABI = [
 {
  inputs: [{ internalType: "address", name: "target", type: "address" }],
  name: "AddressEmptyCode",
  type: "error",
 },
 {
  inputs: [{ internalType: "bytes32", name: "commitment", type: "bytes32" }],
  name: "CommitmentTooNew",
  type: "error",
 },
 {
  inputs: [{ internalType: "bytes32", name: "commitment", type: "bytes32" }],
  name: "CommitmentTooOld",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "implementation", type: "address" }],
  name: "ERC1967InvalidImplementation",
  type: "error",
 },
 { inputs: [], name: "ERC1967NonPayable", type: "error" },
 { inputs: [], name: "FailedInnerCall", type: "error" },
 { inputs: [], name: "InvalidInitialization", type: "error" },
 { inputs: [], name: "MaxCommitmentAgeTooHigh", type: "error" },
 { inputs: [], name: "MaxCommitmentAgeTooLow", type: "error" },
 {
  inputs: [{ internalType: "string", name: "name", type: "string" }],
  name: "NameNotAvailable",
  type: "error",
 },
 { inputs: [], name: "NotInitializing", type: "error" },
 {
  inputs: [{ internalType: "address", name: "owner", type: "address" }],
  name: "OwnableInvalidOwner",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "account", type: "address" }],
  name: "OwnableUnauthorizedAccount",
  type: "error",
 },
 { inputs: [], name: "ResolverRequiredWhenDataSupplied", type: "error" },
 { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
 {
  inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
  name: "UUPSUnsupportedProxiableUUID",
  type: "error",
 },
 {
  inputs: [{ internalType: "bytes32", name: "commitment", type: "bytes32" }],
  name: "UnexpiredCommitmentExists",
  type: "error",
 },
 {
  anonymous: false,
  inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }],
  name: "Initialized",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: false, internalType: "string", name: "name", type: "string" },
   { indexed: true, internalType: "bytes32", name: "label", type: "bytes32" },
   { indexed: true, internalType: "address", name: "owner", type: "address" },
  ],
  name: "NameRegistered",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
   { indexed: true, internalType: "address", name: "newOwner", type: "address" },
  ],
  name: "OwnershipTransferred",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }],
  name: "Upgraded",
  type: "event",
 },
 {
  inputs: [],
  name: "UPGRADE_INTERFACE_VERSION",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "", type: "address" }],
  name: "alreadyRegister",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "string", name: "name", type: "string" }],
  name: "available",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "bytes32", name: "commitment", type: "bytes32" }],
  name: "commit",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  name: "commitments",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "getAlreadyRegister",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "getLoyaltyDiscount",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "contract BaseRegistrarImplementation", name: "_base", type: "address" },
   { internalType: "contract IPriceOracle", name: "_prices", type: "address" },
   { internalType: "uint256", name: "_minCommitmentAge", type: "uint256" },
   { internalType: "uint256", name: "_maxCommitmentAge", type: "uint256" },
   { internalType: "contract ReverseRegistrar", name: "_reverseRegistrar", type: "address" },
   { internalType: "contract INameWrapper", name: "_nameWrapper", type: "address" },
   { internalType: "contract X", name: "_x", type: "address" },
  ],
  name: "initialize",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "loyaltyDiscount",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
  ],
  name: "makeCommitment",
  outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  stateMutability: "pure",
  type: "function",
 },
 {
  inputs: [],
  name: "maxCommitmentAge",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "minCommitmentAge",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "nameWrapper",
  outputs: [{ internalType: "contract INameWrapper", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "owner",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "prices",
  outputs: [{ internalType: "contract IPriceOracle", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "proxiableUUID",
  outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "registerByAirdrop",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "registerByAuction",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "registerByFlashSale",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "registerByGroupPurchase",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "registerByLottery",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "addr", type: "address" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
  ],
  name: "registerByNormal",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "renounceOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "reserve",
  outputs: [{ internalType: "contract IReserveDomain", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "reverseRegistrar",
  outputs: [{ internalType: "contract ReverseRegistrar", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "LD", type: "uint256" }],
  name: "setLoyaltyDiscount",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setPriceOracle",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedAirdrop",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedAuction",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedFlashSale",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedGroupPurchase",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedLottery",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedNormalRegister",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedPool",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "addr", type: "address" }],
  name: "setTrustedReserveDomain",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "bytes4", name: "interfaceID", type: "bytes4" }],
  name: "supportsInterface",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "pure",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
  name: "transferOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedAirdrop",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedAuction",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedFlashSale",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedGroupPurchase",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedLottery",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedNormalRegister",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "trustedPool",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "newImplementation", type: "address" },
   { internalType: "bytes", name: "data", type: "bytes" },
  ],
  name: "upgradeToAndCall",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [{ internalType: "string", name: "name", type: "string" }],
  name: "valid",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "pure",
  type: "function",
 },
]
