export const Goerli_Test_BCQB_ABI = [
 {
  inputs: [
   { internalType: "uint256", name: "numerator", type: "uint256" },
   { internalType: "uint256", name: "denominator", type: "uint256" },
  ],
  name: "ERC2981InvalidDefaultRoyalty",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "receiver", type: "address" }],
  name: "ERC2981InvalidDefaultRoyaltyReceiver",
  type: "error",
 },
 {
  inputs: [
   { internalType: "uint256", name: "tokenId", type: "uint256" },
   { internalType: "uint256", name: "numerator", type: "uint256" },
   { internalType: "uint256", name: "denominator", type: "uint256" },
  ],
  name: "ERC2981InvalidTokenRoyalty",
  type: "error",
 },
 {
  inputs: [
   { internalType: "uint256", name: "tokenId", type: "uint256" },
   { internalType: "address", name: "receiver", type: "address" },
  ],
  name: "ERC2981InvalidTokenRoyaltyReceiver",
  type: "error",
 },
 { inputs: [], name: "InitialRegistryAddressCannotBeZeroAddress", type: "error" },
 { inputs: [], name: "OnlyOwner", type: "error" },
 {
  inputs: [{ internalType: "address", name: "operator", type: "address" }],
  name: "OperatorNotAllowed",
  type: "error",
 },
 { inputs: [], name: "RegistryHasBeenRevoked", type: "error" },
 {
  anonymous: false,
  inputs: [
   { indexed: false, internalType: "address", name: "previousAdmin", type: "address" },
   { indexed: false, internalType: "address", name: "newAdmin", type: "address" },
  ],
  name: "AdminChanged",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "owner", type: "address" },
   { indexed: true, internalType: "address", name: "approved", type: "address" },
   { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
  ],
  name: "Approval",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "owner", type: "address" },
   { indexed: true, internalType: "address", name: "operator", type: "address" },
   { indexed: false, internalType: "bool", name: "approved", type: "bool" },
  ],
  name: "ApprovalForAll",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: true, internalType: "address", name: "beacon", type: "address" }],
  name: "BeaconUpgraded",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: false, internalType: "address", name: "from", type: "address" },
   { indexed: false, internalType: "uint16", name: "chainId", type: "uint16" },
   { indexed: false, internalType: "uint256[]", name: "ids", type: "uint256[]" },
  ],
  name: "CrossEvent",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: false, internalType: "uint8", name: "version", type: "uint8" }],
  name: "Initialized",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: false, internalType: "uint16", name: "_srcChainId", type: "uint16" },
   { indexed: false, internalType: "bytes", name: "_srcAddress", type: "bytes" },
   { indexed: false, internalType: "uint64", name: "_nonce", type: "uint64" },
   { indexed: false, internalType: "bytes", name: "_payload", type: "bytes" },
  ],
  name: "MessageFailed",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: false, internalType: "address", name: "newRegistry", type: "address" }],
  name: "OperatorFilterRegistryAddressUpdated",
  type: "event",
 },
 { anonymous: false, inputs: [], name: "OperatorFilterRegistryRevoked", type: "event" },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
   { indexed: true, internalType: "address", name: "newOwner", type: "address" },
  ],
  name: "OwnershipTransferred",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: false, internalType: "uint16", name: "_remoteChainId", type: "uint16" },
   { indexed: false, internalType: "bytes", name: "_path", type: "bytes" },
  ],
  name: "SetTrustedRemote",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "from", type: "address" },
   { indexed: true, internalType: "address", name: "to", type: "address" },
   { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
  ],
  name: "Transfer",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }],
  name: "Upgraded",
  type: "event",
 },
 {
  inputs: [],
  name: "CANONICAL_CORI_SUBSCRIPTION",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "CANONICAL_OPERATOR_FILTER_REGISTRY_ADDRESS",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint16", name: "_srcChainId", type: "uint16" },
   { internalType: "bytes", name: "_payload", type: "bytes" },
  ],
  name: "_lzReceive",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint256", name: "_QueenBeeID", type: "uint256" },
   { internalType: "uint256", name: "_credits", type: "uint256" },
  ],
  name: "addCredits",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "operator", type: "address" },
   { internalType: "uint256", name: "tokenId", type: "uint256" },
  ],
  name: "approve",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "owner", type: "address" }],
  name: "balanceOf",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "baseExtension",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "baseURI",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
  name: "cost",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "pure",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "_receiver", type: "address" },
   { internalType: "uint16", name: "_dstChainId", type: "uint16" },
   { internalType: "uint256[]", name: "_ids", type: "uint256[]" },
  ],
  name: "crossChain",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [{ internalType: "bool", name: "_state", type: "bool" }],
  name: "crosschainPause",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "crosschainPaused",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint16", name: "_dstChainId", type: "uint16" },
   { internalType: "address", name: "_userApplication", type: "address" },
   {
    components: [
     { internalType: "address", name: "owner", type: "address" },
     { internalType: "uint256[]", name: "ids", type: "uint256[]" },
     { internalType: "uint256[]", name: "boundCredits", type: "uint256[]" },
    ],
    internalType: "struct BeeClubQueenBee.Assets",
    name: "_assets",
    type: "tuple",
   },
   { internalType: "bytes", name: "_adapterParams", type: "bytes" },
  ],
  name: "estimateFees",
  outputs: [{ internalType: "uint256", name: "fee", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint16", name: "", type: "uint16" },
   { internalType: "bytes", name: "", type: "bytes" },
   { internalType: "uint256", name: "", type: "uint256" },
  ],
  name: "failedMessages",
  outputs: [
   { internalType: "uint256", name: "payloadLength", type: "uint256" },
   { internalType: "bytes32", name: "payloadHash", type: "bytes32" },
  ],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "gasForDestinationLzReceive",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
  name: "getApproved",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_QueenBeeID", type: "uint256" }],
  name: "getBoundCredits",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "_address", type: "address" }],
  name: "getContractAllowOrNot",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "getNowId",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "_name", type: "string" },
   { internalType: "string", name: "_symbol", type: "string" },
   { internalType: "uint256", name: "_lock_", type: "uint256" },
   { internalType: "uint256", name: "_gasForDestinationLzReceive", type: "uint256" },
   { internalType: "string", name: "_initBaseURI", type: "string" },
   { internalType: "string", name: "_baseExtension", type: "string" },
  ],
  name: "initialize",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "address", name: "operator", type: "address" },
  ],
  name: "isApprovedForAll",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "isOperatorFilterRegistryRevoked",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "lzEndpoint",
  outputs: [{ internalType: "contract ILayerZeroEndpoint", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint16", name: "_srcChainId", type: "uint16" },
   { internalType: "bytes", name: "_srcAddress", type: "bytes" },
   { internalType: "uint64", name: "_nonce", type: "uint64" },
   { internalType: "bytes", name: "_payload", type: "bytes" },
  ],
  name: "lzReceive",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "maxMintAmount",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_mintAmount", type: "uint256" }],
  name: "mint",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "", type: "address" }],
  name: "mintByUser",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "bool", name: "_state", type: "bool" }],
  name: "mintPause",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "mintPaused",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "name",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "operatorFilterRegistry",
  outputs: [{ internalType: "contract IOperatorFilterRegistry", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "owner",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
  name: "ownerOf",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "proxiableUUID",
  outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "renounceOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "revokeOperatorFilterRegistry",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint256", name: "tokenId", type: "uint256" },
   { internalType: "uint256", name: "salePrice", type: "uint256" },
  ],
  name: "royaltyInfo",
  outputs: [
   { internalType: "address", name: "", type: "address" },
   { internalType: "uint256", name: "", type: "uint256" },
  ],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "from", type: "address" },
   { internalType: "address", name: "to", type: "address" },
   { internalType: "uint256", name: "tokenId", type: "uint256" },
  ],
  name: "safeTransferFrom",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "from", type: "address" },
   { internalType: "address", name: "to", type: "address" },
   { internalType: "uint256", name: "tokenId", type: "uint256" },
   { internalType: "bytes", name: "data", type: "bytes" },
  ],
  name: "safeTransferFrom",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "_address", type: "address" },
   { internalType: "bool", name: "_state", type: "bool" },
  ],
  name: "setAllowContract",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "operator", type: "address" },
   { internalType: "bool", name: "approved", type: "bool" },
  ],
  name: "setApprovalForAll",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "string", name: "_newBaseExtension", type: "string" }],
  name: "setBaseExtension",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "string", name: "_newBaseURI", type: "string" }],
  name: "setBaseURI",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "bool", name: "subscribe", type: "bool" }],
  name: "setCANONICAL",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "receiver", type: "address" },
   { internalType: "uint96", name: "_feeNumerator_", type: "uint96" },
  ],
  name: "setDefaultRoyalty",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_newGas", type: "uint256" }],
  name: "setGasForDestinationLzReceive",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_cost", type: "uint256" }],
  name: "setInitialCost",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "_address", type: "address" }],
  name: "setLzEndpoint",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_max", type: "uint256" }],
  name: "setMaxLimit",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_max", type: "uint256" }],
  name: "setMaxMintAmount",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
  name: "setStartId",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint256", name: "tokenId", type: "uint256" },
   { internalType: "address", name: "receiver", type: "address" },
   { internalType: "uint96", name: "_feeNumerator_", type: "uint96" },
  ],
  name: "setTokenIdRoyalty",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "uint16", name: "_srcChainId", type: "uint16" },
   { internalType: "bytes", name: "_path", type: "bytes" },
  ],
  name: "setTrustedRemote",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "_addr", type: "address" }],
  name: "setWhitelist",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
  name: "supportsInterface",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "symbol",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
  name: "tokenByIndex",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "uint256", name: "index", type: "uint256" },
  ],
  name: "tokenOfOwnerByIndex",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
  name: "tokenURI",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "totalSupply",
  outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "from", type: "address" },
   { internalType: "address", name: "to", type: "address" },
   { internalType: "uint256", name: "tokenId", type: "uint256" },
  ],
  name: "transferFrom",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
  name: "transferOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "bool", name: "_state", type: "bool" }],
  name: "transferPause",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "transferPaused",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "uint16", name: "", type: "uint16" }],
  name: "trustedRemoteLookup",
  outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "newRegistry", type: "address" }],
  name: "updateOperatorFilterRegistryAddress",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "newImplementation", type: "address" }],
  name: "upgradeTo",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "newImplementation", type: "address" },
   { internalType: "bytes", name: "data", type: "bytes" },
  ],
  name: "upgradeToAndCall",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "_owner", type: "address" }],
  name: "walletOfOwner",
  outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "", type: "address" }],
  name: "whitelist",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 { inputs: [], name: "withdraw", outputs: [], stateMutability: "payable", type: "function" },
]
