export const XFlashSale_ABI = [
 {
  inputs: [{ internalType: "address", name: "target", type: "address" }],
  name: "AddressEmptyCode",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "implementation", type: "address" }],
  name: "ERC1967InvalidImplementation",
  type: "error",
 },
 { inputs: [], name: "ERC1967NonPayable", type: "error" },
 { inputs: [], name: "FailedInnerCall", type: "error" },
 { inputs: [], name: "InsufficientValue", type: "error" },
 { inputs: [], name: "InvalidInitialization", type: "error" },
 { inputs: [], name: "NotInitializing", type: "error" },
 {
  inputs: [{ internalType: "address", name: "owner", type: "address" }],
  name: "OwnableInvalidOwner",
  type: "error",
 },
 {
  inputs: [{ internalType: "address", name: "account", type: "address" }],
  name: "OwnableUnauthorizedAccount",
  type: "error",
 },
 { inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
 {
  inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
  name: "UUPSUnsupportedProxiableUUID",
  type: "error",
 },
 {
  anonymous: false,
  inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }],
  name: "Initialized",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
   { indexed: true, internalType: "address", name: "newOwner", type: "address" },
  ],
  name: "OwnershipTransferred",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [{ indexed: true, internalType: "address", name: "implementation", type: "address" }],
  name: "Upgraded",
  type: "event",
 },
 {
  anonymous: false,
  inputs: [
   { indexed: true, internalType: "string", name: "code", type: "string" },
   { indexed: true, internalType: "uint256", name: "startTime", type: "uint256" },
  ],
  name: "launchFSEvent",
  type: "event",
 },
 {
  inputs: [
   { internalType: "string", name: "name", type: "string" },
   { internalType: "address", name: "owner", type: "address" },
   { internalType: "bytes32", name: "secret", type: "bytes32" },
   { internalType: "address", name: "resolver", type: "address" },
   { internalType: "bytes[]", name: "data", type: "bytes[]" },
   { internalType: "bool", name: "reverseRecord", type: "bool" },
   { internalType: "uint16", name: "ownerControlledFuses", type: "uint16" },
   { internalType: "string", name: "URI", type: "string" },
   { internalType: "string", name: "code", type: "string" },
  ],
  name: "FSRegister",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
 {
  inputs: [],
  name: "RC",
  outputs: [{ internalType: "contract IRegisterController", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "UPGRADE_INTERFACE_VERSION",
  outputs: [{ internalType: "string", name: "", type: "string" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [{ internalType: "string", name: "", type: "string" }],
  name: "infoByFS",
  outputs: [
   { internalType: "uint256", name: "startTime", type: "uint256" },
   { internalType: "uint256", name: "duration", type: "uint256" },
   { internalType: "uint256", name: "playerNum", type: "uint256" },
   { internalType: "uint256", name: "maxParticipant", type: "uint256" },
   { internalType: "uint256", name: "discount", type: "uint256" },
  ],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "contract IRegisterController", name: "_RC", type: "address" },
   { internalType: "uint256", name: "_lock_", type: "uint256" },
  ],
  name: "initialize",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "", type: "string" },
   { internalType: "address", name: "", type: "address" },
  ],
  name: "joinRecord",
  outputs: [{ internalType: "bool", name: "", type: "bool" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [
   { internalType: "string", name: "_code", type: "string" },
   { internalType: "uint256", name: "_startTime", type: "uint256" },
   { internalType: "uint256", name: "_duration", type: "uint256" },
   { internalType: "uint256", name: "_maxParticipant", type: "uint256" },
   { internalType: "uint256", name: "_discount", type: "uint256" },
  ],
  name: "launchFlashSale",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [],
  name: "owner",
  outputs: [{ internalType: "address", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "prices",
  outputs: [{ internalType: "contract IPriceOracle", name: "", type: "address" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "proxiableUUID",
  outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  stateMutability: "view",
  type: "function",
 },
 {
  inputs: [],
  name: "renounceOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "contract IPriceOracle", name: "addr", type: "address" }],
  name: "setTrustedPriceOracle",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "contract IRegisterController", name: "addr", type: "address" }],
  name: "setTrustedRegisterController",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
  name: "transferOwnership",
  outputs: [],
  stateMutability: "nonpayable",
  type: "function",
 },
 {
  inputs: [
   { internalType: "address", name: "newImplementation", type: "address" },
   { internalType: "bytes", name: "data", type: "bytes" },
  ],
  name: "upgradeToAndCall",
  outputs: [],
  stateMutability: "payable",
  type: "function",
 },
]
